language: node_js
node_js:
  - "7"
  - "8"
  - "9"
  - "10"
  - "node"
before_install:
  - curl -L https://unpkg.com/@pnpm/self-installer | node
install:
  - pnpm install
after_success:
  - npm run coverage